[package]
description = "Standard library for Osmosis with CosmWasm support included"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "osmosis-std"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmos-sdk-proto = {version = "0.12.3", default-features = false}
cosmwasm-std = {version = "1.0.0", features = ["stargate"]}
osmosis-std-derive = {version = "0.1.0", path = "../osmosis-std-derive"}
prost = "0.10.4"
prost-types = "0.10.1"
