[package]
name = "primitives"
version = "0.1.0"
description = "A cosmwasm template contract with osmosis bindings"
authors = ["Hyungsuk Kang<hskang9@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["stargate"] }
cosmwasm-storage = "1.0.0"
cw-storage-plus = "0.13.2"
cw-controllers = { version = "0.13.4" }
cw-utils = { version = "0.13.4" }
cw2 = "0.13.2"
cw20 = { version = "0.13.4" }
cw721 = { version = "0.13.2" }
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
osmo-bindings = {path="../bindings"}

[dev-dependencies]
cosmwasm-schema = "1.0.0"
cw-multi-test = "0.13.2"

[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
